// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/*import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma 7 removed the schema-level `directUrl` field; this single `url` is what the
  // CLI (validate/generate/migrate/db push/db pull) connects with. It must be a direct
  // (non-pooled) connection because Migrate needs session-scoped advisory locks that
  // Supabase's transaction-mode pooler (DATABASE_URL, pgbouncer=true) can't provide.
  // The running app is unaffected: src/lib/db/prisma.ts wires its own PrismaPg adapter
  // straight to DATABASE_URL, bypassing this config entirely.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
*/

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});